apiVersion: auth.vault.upbound.io/v1alpha1
kind: Backend
metadata:
  name: approle
spec:
  forProvider:
    type: approle
  providerConfigRef:
    name: default
---
apiVersion: approleauth.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  name: approle
spec:
  forProvider:
    backendRef:
      name: approle
    roleName: test-role
  providerConfigRef:
    name: default
---
apiVersion: approleauth.vault.upbound.io/v1alpha1
kind: AuthBackendRoleSecretID
metadata:
  name: approle-secret
spec:
  forProvider:
    backendRef:
      name: approle
    roleNameRef:
      name: approle
  providerConfigRef:
    name: default