apiVersion: kubernetesauth.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  name: kubernetes-auth-role
spec:
  forProvider:
    backendRef:
      name: kubernetes
    roleName: test
    boundServiceAccountNames:
      - test
    boundServiceAccountNamespaces:
      - test
    tokenPolicies:
      - policy
  providerConfigRef:
    name: default