apiVersion: kubernetesauthbackendrole.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  name: hello-crossplane3
spec:
  forProvider:
    backend: kubernetes
    roleName: test3
    boundServiceAccountNames:
      - test-service-account
    boundServiceAccountNamespaces:
      - test-namespace
    tokenTtl: 0
    tokenPolicies:
      - "some policy"
  providerConfigRef:
    name: default